# Generated by Django 4.0.6 on 2022-09-10 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propiedad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitanteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=255, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('placas', models.CharField(max_length=5, verbose_name='Placas')),
                ('telefono', models.CharField(max_length=15, null=True, verbose_name='Télefono')),
                ('comentarios', models.CharField(max_length=300, verbose_name='Detalles')),
                ('is_vehiculo', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('fk_propiedad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='propiedad.propiedadmodel')),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
            },
        ),
    ]
