# Generated by Django 4.0.6 on 2022-09-10 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casillero', '0001_initial'),
        ('auditoria_pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriapedidomodel',
            name='fk_casillero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='casillero.casilleromodel'),
        ),
    ]
