# Generated by Django 4.0.6 on 2022-09-10 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
        ('auditoria_pedido', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriapedidomodel',
            name='fk_persona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.personmodel'),
        ),
        migrations.AddField(
            model_name='auditoriapedidomodel',
            name='fk_usuario_entrega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
