# Generated by Django 4.0.6 on 2022-09-10 02:57

import apps.conjunto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConjuntoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Correo Electrónico')),
                ('telephone', models.CharField(blank=True, max_length=10, verbose_name='Telefono')),
                ('logo', models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.conjunto.models.img_directori, verbose_name='Logo del conjunto')),
                ('imagen', models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.conjunto.models.img_directori, verbose_name='Imagen del conjunto')),
                ('adress', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('about', models.CharField(blank=True, max_length=255, verbose_name='Acerca de nosotros')),
                ('eslogan', models.CharField(blank=True, max_length=255, verbose_name='Eslogan')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Conjunto',
                'verbose_name_plural': 'Conjuntos',
            },
        ),
    ]
