# Generated by Django 4.0.6 on 2022-09-10 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo_vehiculo', '0001_initial'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=255, verbose_name='Detalles')),
                ('anio', models.CharField(max_length=4, verbose_name='Detalles')),
                ('identificador', models.CharField(max_length=4, verbose_name='Placa/Número identificador')),
                ('comentarios', models.CharField(max_length=255, unique=True, verbose_name='Detalles')),
                ('is_acceso_parqueadero', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('fk_persona', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.personmodel')),
                ('fk_tipo_vehiculo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tipo_vehiculo.tipovehiculomodel')),
            ],
            options={
                'verbose_name': 'Vehiculo',
                'verbose_name_plural': 'Vehiculos',
            },
        ),
    ]
