# Generated by Django 4.0.6 on 2022-09-10 03:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculo', '0001_initial'),
        ('parqueadero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculoParqueaderoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_asignado', models.CharField(max_length=255, verbose_name='Número de parqueadero asignado')),
                ('comentarios', models.CharField(max_length=255, null=True, verbose_name='Detalles')),
                ('is_visitante', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('hora_acceso', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hora Ingreso|')),
                ('fk_parqueadero', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parqueadero.parqueaderomodel')),
                ('fk_vehiculo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vehiculo.vehiculomodel')),
            ],
            options={
                'verbose_name': 'VehiculoParqueadero',
                'verbose_name_plural': 'AuditoriaPedidos',
            },
        ),
    ]
