# Generated by Django 4.0.6 on 2022-09-10 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculo_parqueadero', '0001_initial'),
        ('visitante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculoparqueaderomodel',
            name='fk_visitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visitante.visitantemodel'),
        ),
    ]
